#ifndef DRIVER_TPA626_H
#define DRIVER_TPA626_H
#define CURRENT_MEASUREMENT_RESOLUTION (0.0001) // Amp/bit
#define SHUNT_RESISTOR_RESISTANCE (0.005) // Ohm
#define CALIBRATIOON_REGISTER_VALUE ((int)(0.00512 / CURRENT_MEASUREMENT_RESOLUTION / SHUNT_RESISTOR_RESISTANCE))
enum {
	TPA626_REGISTER_CONFIGURATION = 0,
	TPA626_REGISTER_SHUNT_VOLTAGE = 1,
	TPA626_REGISTER_BUS_VOLTAGE = 2,
	TPA626_REGISTER_POWER = 3,
	TPA626_REGISTER_CURRENT = 4,
	TPA626_REGISTER_CALIBRATION = 5,
	TPA626_REGISTER_UNIQUE_ID = 255,
};
void tpa626_task(void *arg);
int tpa626_info(struct task_descriptor *task, char *dest);
#endif // DRIVER_TPA626_H
